site_name: Gothic Modding Community
site_url: https://auronen.github.io/gmc/

repo_name: auronen/gmc
repo_url: https://github.com/auronen/gmc/
edit_uri: edit/main/docs/

theme:
  name: material
  favicon: img/gmc_logo.png
  logo: img/gmc_logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: light blue
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Home:
    - index.md
    - Getting Started: GettingStarted_ZenGin.md
    - ZenGin (G1/G2): zengin/general_info/DirectoryStructure.md
    - Genome (G3/R1): genome/index.md
  - ZenGin (G1/G2):
    - General information:
      - Directory structure: zengin/general_info/DirectoryStructure.md
      - VDFS - virtual file system: 
        - zengin/general_info/vdfs/index.md
        - GothicVDFS:       zengin/tools/GothicVDFS.md
        - VDFS Tool:        zengin/tools/VDFSTool.md
      - Object persistence: zengin/general_info/ObjectPersistence.md

    - Animations: 
      - zengin/anims/index.md
      - MDS - ModelScript: zengin/anims/MDS.md
      - EventBlocks: zengin/anims/AniEventBlocks.md
      - Tutorials:
        - Standalone animation: zengin/anims/StandaloneAni.md

    - Meshes: 
      - zengin/meshes/index.md

    - Music: 
      - zengin/music/index.md

    - Sound:
      - zengin/sound/index.md

    - Textures:
      - zengin/textures/index.md

    - Video:
      - zengin/video/index.md

    - Worlds:
      - zengin/worlds/index.md

    - Scripts: 
      - zengin/scripts/index.md
      - Classes:
        - C_INFO: zengin/scripts/classes/c_info.md
        - C_ITEM: zengin/scripts/classes/c_item.md
        - C_SVM:  zengin/scripts/classes/c_svm.md
      - Extenders:
        - zengin/scripts/extenders/index.md
        - Ikarus:
          - zengin/scripts/extenders/ikarus/index.md
        - LeGo:
          - zengin/scripts/extenders/lego/index.md
          - Talents:         zengin/scripts/extenders/lego/Talents.md
          - Bars:            zengin/scripts/extenders/lego/Bars.md
          - ItemHelper:      zengin/scripts/extenders/lego/ItemHelper.md
          - ConsoleCommands: zengin/scripts/extenders/lego/ConsoleCommands.md
          - Trialoge:        zengin/scripts/extenders/lego/Trialoge.md
          - Misc:            zengin/scripts/extenders/lego/Misc.md
        - AFSP:
          - zengin/scripts/extenders/afsp/index.md
          - Enhanced Info Manager: zengin/scripts/extenders/afsp/afsp_eim.md
        - zParserExtender: 
          - zengin/scripts/extenders/zParserExtender/index.md
          - Syntax extensions:
            - While loop:         zengin/scripts/extenders/zParserExtender/while.md
            - Namespaces:         zengin/scripts/extenders/zParserExtender/namespaces.md
            - Event functions:    zengin/scripts/extenders/zParserExtender/events.md
            - Test-else binding:  zengin/scripts/extenders/zParserExtender/testelse.md
            - Extern binding:     zengin/scripts/extenders/zParserExtender/extern.md
            - Dialogue constants: zengin/scripts/extenders/zParserExtender/dialogues.md
          - Classes:
            - C_Trigger class:    zengin/scripts/extenders/zParserExtender/c_trigger.md
            - Engine classes:     zengin/scripts/extenders/zParserExtender/helperclasses.md
#           - External functions: zengin/scripts/extenders/zPArserExtender/externals.md
          - Daedalus Injection:
            - zengin/scripts/extenders/zParserExtender/injection.md
            - META block:     zengin/scripts/extenders/zParserExtender/META.md
            - Hooking:        zengin/scripts/extenders/zParserExtender/hooks.md
            - Other features: zengin/scripts/extenders/zParserExtender/other.md
          - Externals:
            - zengin/scripts/extenders/zParserExtender/externals/index.md
            - String functions: zengin/scripts/extenders/zParserExtender/externals/string.md
            - Menu function:    zengin/scripts/extenders/zParserExtender/externals/menu.md
            - Log function:     zengin/scripts/extenders/zParserExtender/externals/log.md
            - Event function:   zengin/scripts/extenders/zParserExtender/externals/eventsandvars.md
            - CAST functions:   zengin/scripts/extenders/zParserExtender/externals/CAST.md
            - HLP functions:    zengin/scripts/extenders/zParserExtender/externals/HLP.md
            - WLD functions:    zengin/scripts/extenders/zParserExtender/externals/WLD.md
            - MDL functions:    zengin/scripts/extenders/zParserExtender/externals/MDL.md
            - NPC functions:    zengin/scripts/extenders/zParserExtender/externals/NPC.md
            - MOB functions:    zengin/scripts/extenders/zParserExtender/externals/MOB.md
            - AI functions:     zengin/scripts/extenders/zParserExtender/externals/AI.md
            - PAR functions:    zengin/scripts/extenders/zParserExtender/externals/PAR.md
            - VOB functions:    zengin/scripts/extenders/zParserExtender/externals/VOB.md
          - Examples:
            - Sign post example: zengin/scripts/extenders/zParserExtender/examples/signposts.md


    - Union:
      - zengin/union/index.md
#      - zParserExtender:
#        - zengin/scripts/extenders/zPArserExtender/index.md


    - Tools:
      - zengin/tools/index.md
      - Daedalus:
        - Daedalus Language Server: zengin/tools/DLS.md
      - VDFS tools:
        - GothicVDFS: zengin/tools/GothicVDFS.md
        - VDFS Tool:  zengin/tools/VDFSTool.md

  - Genome (G3/R1):
    - General information: 
      - genome/index.md
      - Object persistence: genome/ObjectPersistence.md
    - Tools:
      - genome/tools/index.md


extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js
  
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mCpS5b5SUY
      name: Gothic Modding Comunity Discord Server
    - icon: fontawesome/brands/github
      link: https://github.com/auronen/gmc
      name: Gothic Modding Comunity Github repository



markdown_extensions:
  - toc:
      permalink: ""
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "100%"
  - git-revision-date-localized:
      enabled: !ENV [GMC_SHOW_UPDATE_TIME, False]
      type: iso_datetime
      timezone: Europe/Warsaw
      exclude:
        - index.md
