site_name: Gothic Modding Community
site_url: https://gothic-modding-community.github.io/gmc/
site_description: 'Gothic Modding Community is a collection of helpful resources for modding Gothic and Risen games.'

repo_name: Gothic-Modding-Community/gmc
repo_url: https://github.com/Gothic-Modding-Community/gmc/
edit_uri: edit/main/docs/

watch:
  - overrides

hooks:
  - overrides/.hooks/language_flags.py
  - overrides/.hooks/git_redirects.py
  - overrides/.hooks/social_patch.py

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/gmc_logo.png
  logo: assets/images/gmc_logo.png
  font:
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
    alternate: material/earth
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: light blue
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mCpS5b5SUY
      name: Gothic Modding Community Discord Server
    - icon: fontawesome/brands/github
      link: https://github.com/Gothic-Modding-Community/gmc
      name: Gothic Modding Community GitHub repository



markdown_extensions:
  - toc:
      permalink: ""
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      linenums: true
      anchor_linenums: true
      # This sets the same ID for the <a> and <span> tags,
      # it's required for the <a> links to work and to allow <span> highlighting via JavaScript
      line_anchors: example
      line_spans: example
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['./overrides/.snippets/']
      check_paths: true
      url_download: true
      url_max_size: 5000000
      url_timeout: 5
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - awesome-pages:
      order: asc
      sort_type: natural
      order_by: title
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "100%"
  - minify:
      minify_html: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      minify_css: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      minify_js: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      cache_safe: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/stylesheets/extra.css
      js_files:
        - assets/javascripts/extra.js
  - i18n:
      default_language: !ENV [GMC_DEFAULT_LANG, en]
      default_language_only: !ENV [GMC_ONLY_DEFAULT_LANG, False]
      languages:
        en:
          name: en - English
          # Disable the /en/ path, a duplicate of the `default_language` build.
          build: false
        pl:
          name: pl - Polski
          build: true
          site_description: 'Gothic Modding Community to zbiór pomocnych materiałów do modowania gier Gothic i Risen.'
        cs:
          name: cs - Čeština
          build: true
          site_description: 'Dokumentace, návody a články zaměřené na modování her Gothic a Risen.'
      material_alternate: true
      # Only 1 global scope, if 2 nav elements are named the same, input translation only once.
      # Translate only the section/directory titles, page titles should be in the meta header of the `.md` file.
      nav_translations:
        en:
          Afsp: AFSP
          Anims: Animations
          Contribute: How To Contribute
          Daedalus tools: Daedalus
          General info: General information
          Genome: Genome (G3/R1)
          Lego: LeGo
          Vdfs tools: VDFS
          Zengin: ZenGin (G1/G2)
          Zgamepad: zGamePad
          Zparserextender: zParserExtender
        pl:
          Anims: Animacje
          Applications: Zastosowania
          Classes: Klasy
          Contribute: Jak Się Udzielić
          Examples: Przykłady
          Extensions: Rozszerzenia
          Functions: Funkcje
          General info: Informacje ogólne
          Home: Strona Główna
          Plugins: Wtyczki
          Scripts: Skrypty
          Syntax extensions: Rozszerzenia składni
          Tools: Narzędzia
          Tutorials: Poradniki
          Various: Różne
  - git-revision-date-localized:
      enabled: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      type: iso_datetime
      timezone: Europe/Warsaw
      exclude:
        - index*.md
        - genome/index*.md
        - zengin/index*.md
  - redirects:
      # Empty dict to fill with the `meta_redirects.py` hook.
      redirect_maps: {}
  - social:
      cards: !ENV [GMC_ENABLE_ON_PUBLISH, False]