site_name: Gothic Modding Community
site_url: https://gothic-modding-community.github.io/gmc/

repo_name: Gothic-Modding-Community/gmc
repo_url: https://github.com/Gothic-Modding-Community/gmc/
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/gmc_logo.png
  logo: assets/images/gmc_logo.png
  icon:
    repo: fontawesome/brands/github
    alternate: material/earth
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: light blue
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view

nav:
  - Home:
    - index.md
    - ZenGin (G1/G2): zengin/index.md
    - Genome (G3/R1): genome/index.md
    - How To Contribute: contribute/index.md

  - ZenGin (G1/G2):
    - zengin/index.md
    - General information:
      - Directory structure: zengin/general_info/directory_structure.md
      - VDFS - virtual file system: zengin/general_info/vdfs.md
      - Object persistence: zengin/general_info/object_persistence.md

    - Animations:
      - zengin/anims/index.md
      - MDS - ModelScript: zengin/anims/mds.md
      - EventBlocks: zengin/anims/events.md
      - Tutorials:
        - Standalone animation: zengin/anims/standalone_ani.md

    - Meshes: zengin/meshes.md

    - Music: zengin/music.md

    - Sound: zengin/sound.md

    - Textures: zengin/textures.md

    - Video: zengin/video.md

    - Worlds:
      - zengin/worlds/index.md
      - Spacer: zengin/worlds/spacer.md

    - Scripts:
      - zengin/scripts/index.md
      - Classes:
        - C_INFO: zengin/scripts/classes/c_info.md
        - C_ITEM: zengin/scripts/classes/c_item.md
        - C_SVM:  zengin/scripts/classes/c_svm.md
      - Extenders:
        - zengin/scripts/extenders/index.md
        - Ikarus:
          - zengin/scripts/extenders/ikarus/index.md
          - Ini File Access: zengin/scripts/extenders/ikarus/ini_access.md
        - LeGo:
          - zengin/scripts/extenders/lego/index.md
          - AI_Function:     zengin/scripts/extenders/lego/ai_function.md
          - Bars:            zengin/scripts/extenders/lego/bars.md
          - Bloodsplats:     zengin/scripts/extenders/lego/bloodsplats.md
          - ConsoleCommands: zengin/scripts/extenders/lego/console_commands.md
          - Dialoggestures:  zengin/scripts/extenders/lego/dialoggestures.md
          - Focusnames:      zengin/scripts/extenders/lego/focusnames.md
          - FrameFunctions:  zengin/scripts/extenders/lego/frame_functions.md
          - GameState:       zengin/scripts/extenders/lego/gamestate.md
          - ItemHelper:      zengin/scripts/extenders/lego/item_helper.md
          - Locals:          zengin/scripts/extenders/lego/locals.md
          - Misc:            zengin/scripts/extenders/lego/misc.md
          - Random:          zengin/scripts/extenders/lego/random.md
          - Talents:         zengin/scripts/extenders/lego/talents.md
          - Timer:           zengin/scripts/extenders/lego/timer.md
          - Trialoge:        zengin/scripts/extenders/lego/trialoge.md
        - AFSP:
          - zengin/scripts/extenders/afsp/index.md
          - Enhanced Info Manager: zengin/scripts/extenders/afsp/afsp_eim.md
        - zParserExtender:
          - zengin/scripts/extenders/zparserextender/index.md
          - Syntax extensions:
            - While loop:         zengin/scripts/extenders/zparserextender/while.md
            - Namespaces:         zengin/scripts/extenders/zparserextender/namespaces.md
            - Event functions:    zengin/scripts/extenders/zparserextender/events.md
            - Test-else binding:  zengin/scripts/extenders/zparserextender/testelse.md
            - Extern binding:     zengin/scripts/extenders/zparserextender/extern.md
            - Dialogue constants: zengin/scripts/extenders/zparserextender/dialogues.md
          - Classes:
            - C_Trigger class:    zengin/scripts/extenders/zparserextender/c_trigger.md
            - Engine classes:     zengin/scripts/extenders/zparserextender/helperclasses.md
#           - External functions: zengin/scripts/extenders/zparserextender/externals.md
          - Daedalus Injection:
            - zengin/scripts/extenders/zparserextender/injection.md
            - META block:     zengin/scripts/extenders/zparserextender/meta.md
            - Hooking:        zengin/scripts/extenders/zparserextender/hooks.md
            - Other features: zengin/scripts/extenders/zparserextender/other.md
          - Externals:
            - String functions: zengin/scripts/extenders/zparserextender/externals/string.md
            - Menu function:    zengin/scripts/extenders/zparserextender/externals/menu.md
            - Log functions:     zengin/scripts/extenders/zparserextender/externals/log.md
            - Event function:   zengin/scripts/extenders/zparserextender/externals/events_vars.md
            - CAST functions:   zengin/scripts/extenders/zparserextender/externals/cast.md
            - HLP functions:    zengin/scripts/extenders/zparserextender/externals/hlp.md
            - WLD functions:    zengin/scripts/extenders/zparserextender/externals/wld.md
            - MDL functions:    zengin/scripts/extenders/zparserextender/externals/mdl.md
            - NPC functions:    zengin/scripts/extenders/zparserextender/externals/npc.md
            - MOB functions:    zengin/scripts/extenders/zparserextender/externals/mob.md
            - AI functions:     zengin/scripts/extenders/zparserextender/externals/ai.md
            - PAR functions:    zengin/scripts/extenders/zparserextender/externals/par.md
            - VOB functions:    zengin/scripts/extenders/zparserextender/externals/vob.md
          - Examples:
            - Sign post example: zengin/scripts/extenders/zparserextender/examples/signposts.md

    - Union plugins:
      - zengin/union/index.md
      - zGamePad:
        - zengin/union/zgamepad/index.md
        - Controls customization: zengin/union/zgamepad/controls.md
        - Gamepad key list: zengin/union/zgamepad/keys_gamepad.md
        - Engine logical key list: zengin/union/zgamepad/keys_engine_logical.md
        - Engine absolute key list: zengin/union/zgamepad/keys_engine_absolute.md
        - Logical function list: zengin/union/zgamepad/logical_functions.md

    - Tools:
      - zengin/tools/index.md
      - Daedalus:
        - Daedalus Language Server: zengin/tools/dls.md
      - VDFS tools:
        - GothicVDFS: zengin/tools/gothic_vdfs.md
        - VDFS Tool:  zengin/tools/vdfs_tool.md

  - Genome (G3/R1):
    - genome/index.md
    - General information:
      - Object persistence: genome/object_persistence.md

    - Tools:
      - genome/tools/index.md

  - How To Contribute:
    - contribute/index.md


extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mCpS5b5SUY
      name: Gothic Modding Comunity Discord Server
    - icon: fontawesome/brands/github
      link: https://github.com/Gothic-Modding-Community/gmc
      name: Gothic Modding Comunity Github repository



markdown_extensions:
  - toc:
      permalink: ""
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      # This sets the same ID for the <a> and <span> tags,
      # it's required for the <a> links to work and to allow <span> highlighting via JavaScript
      line_anchors: example
      line_spans: example
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['./docs/assets/sources/']
      check_paths: true
      url_download: true
      url_max_size: 5000000
      url_timeout: 5
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "100%"
  - minify:
      minify_html: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      minify_css: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      minify_js: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      cache_safe: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/stylesheets/extra.css
      js_files:
        - assets/javascripts/extra.js
  - i18n: # TODO optimize local usage to build page based on environmental variables
      default_language: en
      languages:
        en:
          name: en - English
          build: true
        pl:
          name: pl - Polski
          build: true
      material_alternate: true
      nav_translations: # Only 1 global scope, if 2 nav elements are named the same, input translation only once
        pl:
          Home: Strona Główna
          How To Contribute: Jak Się Udzielać
  - git-revision-date-localized:
      enabled: !ENV [GMC_ENABLE_ON_PUBLISH, False]
      type: iso_datetime
      timezone: Europe/Warsaw
      exclude:
        - index*.md
        - genome/index*.md
        - zengin/index*.md
