name: Dev Site

on:
  push:
    branches:
      - dev

env:
  GMC_ENABLE_ON_PUBLISH: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history.
          # Default: 1
          # 0 is needed for the update time plugin to work properly
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run prebuild tests
        run: python -m unittest discover tests/ -v
      - name: Build and deploy site
        run: mkdocs gh-deploy --force --remote-branch gh-dev-page